import type { Post } from "@opti/sanity"
import { type } from "arktype"
import type { HTMLAttributes } from "react"

//This will eventually be the types generated by sanity.
// We can still use arktype to help extract useful bits of information.

export const FeaturedPostSchema = type({
	_id: "string",
	title: "string",
	excerpt: "string",
	featureImage: "string",
	slug: "string?",
	category: "string?",
})

export type FeaturedPostType = typeof FeaturedPostSchema.infer

export interface FeaturedPostProps extends Omit<Pick<Post, keyof Omit<FeaturedPostType, "slug" | "category">>, "featureImage"> {
	className?: string
	slug?: string
	category?: string
	featureImage?: string
}

export const BlogPostThumbnailSchema = type({
	title: "string",
	excerpt: "string|null",
	featureImage: "string|null",
	slug: "string",
})

export type BlogPostThumbnailType = typeof BlogPostThumbnailSchema.infer

export interface BlogPostThumbnailProps
	extends Omit<HTMLAttributes<HTMLElement>, keyof BlogPostThumbnailType>,
		BlogPostThumbnailType {}
